## Main findings

Our objective was to identify causal effects for COVID-19 cases. We found that weather affects the reported number of infections, especially temperature (which has a reducing effect on case numbers) and rainfall (which increases case numbers). We saw that reports of high case numbers in districts led to a reduction in new infection numbers, which indicates risk-averse awareness in the population. The overall effect of mobility showed no consistent effect, however, in specific areas significant causal effects could be measured: Increasing activity in retail and recreational areas increased reported case numbers, while increased movement for essential shopping (grocery and pharmacy) led to reduced case numbers.

Furthermore, we made a strong case for the use of causal DAGs in epidemiology and a pandemic like COVID-19: DAGs allow to choose confounders for the analysis in a principled and statistically correct way while reducing possible causes for bias. Also, the DAG formalization allows for discussion about the underlying causal structure.

## Comparison with previous research

Most research on determinants affecting case numbers of COVID-19 is restricted to single aspects [@fowler_effect_2020;@li_retrospective_2020;@shi_impact_2020;@Wang2020temperature]. To reliably identify causal drivers, one needs to adjust for confounders. To this end, we used an integrated model with variables from different aspects like mobility, awareness, weather, or socio-demographics and identified confounders by causal analysis with a directed acyclic graph. A causal approach is used in another current COVID-19 analysis [@gencoglu2020causal]. There, however, they identify the causal relationships (reconstruct a DAG), while we estimated causal effects for a given hypothesized DAG.

Several studies assessing the impact of public health measures on mobility have each observed a downward trend accompanied by a decrease in the number of newly reported cases [@chang_modeling_2020;@cowling2020impact;@fowler_effect_2020;@kraemer_effect_2020;@lai_effect_2020;@linka_outbreak_2020].

Our findings regarding awareness/Google Trends analysis are in good agreement with the correlations found by @effenberger_association_2020, @higgins_correlations_2020, and @yuan_trends_2020, who conclude that alertness to COVID-19 rises several days before the highest number of cases are reported. At this point it should be noted, that awareness is substantially influenced by public media coverage, which should be considered, if possible, in future studies [@higgins_correlations_2020]. As such, awareness is difficult to measure and here the number of Google searches for "corona" could only be a proxy for this concept.

In addition, in alignment with other recent published studies, our results confirm evidence which associated a negative effect of temperature on new COVID-19 cases [@bannister-tyrrell_preliminary_2020;@demongeot_temperature_2020;@liu_impact_2020;@qi_covid-19_2020;@shi_impact_2020;@sobral_association_2020;@tosepu_correlation_2020;@Wang2020temperature;@wu_effects_2020]. It is however controversial to other scientific literature describing no effects [@briz-redon_spatio-temporal_2020;@iqbal_nexus_2020;@jahangiri_sensitivity_2020;@juni_impact_2020;@yao_no_2020] or even converse correlations [@auler_evidence_2020;@xie_association_2020]. The conflicting results might be explained by different climates and characteristics of the populations under study. While we are confident that our strict causal analysis resulted in effect estimates as undistorted as possible, there might be unconsidered bias in those other studies. Further research needs to be done to elucidate the biological characteristics of the novel virus SARS-CoV-2 regarding its ambient temperature survival and transmission. Finally, we found a positive causal effect of increment precipitation and a raise in COVID-19 cases, which supports previous observations [@sobral_association_2020].

## Limitations and strengths

While use of a causal DAG is itself a strong tool to identify causal effects (and not just statistical associations), it introduces two limitations: causal assumptions within the graph (depicted by edges) need to be well justified, and the statistical regression model that calculates total causal effects needs to be appropriate for the task at hand. We endorse our graph as a basis for discussion on residual confounding. We did not try to construct the DAG from the available data (cf. [@gencoglu2020causal]). As such, our proposed DAG is not entirely consistent with the data and there are conditional dependencies between variables that cannot be dissolved by adding edges to the DAG (e.g. between the policies like contact restrictions and mandatory face masks). Another way to identify potential problems in the proposed DAG is to perform a sensitivity analysis of its structure by inspecting its maximal ancestral graph (MAG) or its Markov equivalence class represented by a complete partially DAG (CPDAG) and the existence of valid adjustment sets for these generalized graphs [@perkovic2017complete]. For the MAG derived from our DAG, only the effects for exposures mobility and searches for corona can be estimated with valid adjustment sets, while for the Markov equivalence class all exposures but COVID-19 burden lead to valid adjustments sets. A further analysis of these implications is out of the scope of this paper.

We observed overdispersion and a substantial increase in model performance with a negative binomial regression compared to Poisson regression, which is in line with the results on COVID-19 daily case counts of @kraemer_effect_2020 and others [@liu_impact_2020;@bannister-tyrrell_preliminary_2020;@Islamm2743]. We did not model case counts with a differential equation model like the classic SIR-model [@kermack1991contributions] and its successors, since these are more suited to prediction [e.g. @rkimodellierung] while our choice of a negative binomial regression framework allowed us to estimate the effects of confounders more reliably. There are more advanced statistical methods for count data, e.g. zero-inflated models and mixed models. We tested both approaches as extensions to the negative binomial regression and experienced numerical problems and increased computing time, along with an insubstantial increase in model performance. Furthermore, our model assumed that all variables have effects proportional to the size of their measurements. It is possible that some variables show saturation effects or opposite effects for lower, medium, or high values. This could be modelled with polynomial or other transformations of the variables, which we did not employ due to limited temporal and spatial data availability. Use of a fixed DAG with effect estimation via regression assumes that data was generated by the same underlying process for the observation period. By inclusion of the successive mitigation policies as binary variables we were able to explain some of the variance caused by the changing dynamics of case numbers (similar to [@Islamm2743]).

We stress the point that our effects were deduced on an aggregate (district) level in the absence of available data on an individual level. As such, conclusions about effects cannot be transferred on individuals without the possibility for an ecological fallacy. Furthermore, as we were using administrative data for our analysis, the results are susceptible to the Modifiable Area Unit Problem (MAUP) [@Openshaw1984]. The MAUP postulates that different regional aggregations of the units of observation may lead to different results and conclusions. Due to limited available data for the different variables, there is currently no way to overcome these problems that are inherent to all analyses on aggregated data level. 

Our observation period was restricted to succession from late winter to spring and summer (February to July). Nevertheless, this transition with increasing temperature was a natural experiment that allowed clues on weather effects.

We could not include data on health care utilization during the pandemic into our models due to the lack of available resources. This is planned for a later follow up to this paper since we rank health care utilization and mobility within health care facilities among the strong factors for COVID-19 progression: personnel in hospitals and private practices is particularly exposed to infection, while the lack of adequate care for other diseases has severe effects on general health of the population. At the same time, health care facilities are key for testing and surveillance of COVID-19 patients.

While our analysis focused on Germany and its districts, we assume that results may be transferred to other countries by adjusting for their respective weather conditions, mobility habits, socio-demographic characteristics, and other determining factors.

The code and resources for our analysis are available on Github, we invite other researchers to replicate our analysis with different assumptions using the files provided in the repository^[The repository is located here: https://github.com/zidatalab/causalcovid19] of the article.

## Discussion of causal effects

In our analysis, the adverse effect of mobility in retail/recreation and the favorable effect of mobility in grocery/pharmacy indicate that policies like contact restrictions which limit the number of individual interactions can lead to reduced infection numbers. This is due to retail/recreational areas encompassing mostly places of social gatherings like restaurants and bars, malls, sports and music venues, among others, while if people are doing more of their essential shopping at supermarkets, they will most likely stay at home with less contact to other people.

The causal effects of awareness measured via searches for "corona" and the COVID-19 burden are harder to interpret. We assume that within our model, the searches for "corona" are an insufficient proxy for awareness, while the decreasing effect for future case numbers of high daily COVID-19 burden numbers indicates it affects individual risk-behavior as a deterrent.

Similarly, the effects of temperature and rainfall can be interpreted as causal effects for indoor and outdoor activities, such that higher temperatures and low rainfall indicate more people spending time outdoor while lower temperatures and high rainfall result in indoor activities, which lead to more infections. In this light, we advocate for precautious measures like increased hygiene, face masks, and air ventilation for unavoidable indoor activities.

## Conclusions

To the best of our knowledge, this is the most comprehensive analysis of causes for COVID-19 infections which integrates different data sources (all publicly available). Causal reasoning with a DAG allows us to estimate the causal effects more reliably.

Our findings suggest that the causal effects of mobility, awareness, and weather need to be taken strongly into account when deciding for mitigation and suppression measures, depending on the recent and future COVID-19 pandemic development.